'use client';

import React, { useState } from 'react';
import { RefreshCw } from 'lucide-react';

export const seoData = {
  whatIs: `The Property Value Estimator determines the investment value of commercial or residential rental real estate using Net Operating Income (NOI) and capitalization rate percentages.`,
  formula: `Real estate capitalization rates dictate property valuation:

$$\\text{Property Value} = \\frac{\\text{Net Operating Income (NOI)}}{\\text{Capitalization Rate \\%} / 100}$$`,
  example: `**Estimate valuation for a property generating $24,000 in annual NOI with a target 6% Cap Rate:**
- Property Value = 24,000 / 0.06 = **$400,000**.`,
  faqs: [
    {
      q: 'What is Net Operating Income (NOI)?',
      a: 'Net Operating Income (NOI) is the total annual income generated by a property (rent, parking, laundry) minus all necessary operating expenses (taxes, insurance, utilities, maintenance, property management). It excludes mortgage payments and depreciation.',
    },
    {
      q: 'What is a Capitalization Rate (Cap Rate)?',
      a: 'A Cap Rate is the rate of return on a real estate investment property based on the income it is expected to generate. It is used to estimate the investor\'s potential return on their investment.',
    },
    {
      q: 'Does a higher Cap Rate mean a better deal?',
      a: 'Not necessarily. A higher Cap Rate implies higher potential returns, but it also reflects higher risk (e.g., higher vacancy rates, deteriorating neighborhood, or aging building infrastructure). Lower Cap Rates typically correspond to safer, premium assets.',
    },
  ],
};

export default function PropertyValueEstimator() {
  const [noi, setNoi] = useState<number>(24000);
  const [capRate, setCapRate] = useState<number>(6);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const handleReset = () => {
    setNoi(24000);
    setCapRate(6);
    setErrors({});
  };

  // Computations
  let results = null;
  const isValid = !isNaN(noi) && noi >= 0 && !isNaN(capRate) && capRate > 0;

  if (isValid) {
    const propertyValue = noi / (capRate / 100);
    results = {
      propertyValue,
    };
  }

  const handleCalculate = () => {
    const newErrors: Record<string, string> = {};
    if (noi < 0 || isNaN(noi)) newErrors.noi = 'NOI cannot be negative';
    if (capRate <= 0 || isNaN(capRate)) newErrors.capRate = 'Cap rate must be greater than zero';
    setErrors(newErrors);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleCalculate();
    }
  };

  return (
    <div className="space-y-8" onKeyDown={handleKeyDown}>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Input Panel */}
        <div className="lg:col-span-5 rounded-2xl border border-border bg-card p-6 shadow-sm">
          <h2 className="text-xl font-bold text-foreground mb-6">Investment Parameters</h2>

          <div className="space-y-5">
            <div>
              <label htmlFor="annual-noi" className="block text-sm font-semibold text-foreground/80 mb-2">Net Operating Income (NOI, $/yr)</label>
              <input
                id="annual-noi"
                type="number"
                value={noi}
                onChange={(e) => { setNoi(Number(e.target.value)); setErrors({}); }}
                className="block w-full py-3 px-4 text-sm font-medium rounded-xl border border-border bg-background outline-none focus:border-primary text-foreground/80"
              />
              {errors.noi && <p className="text-xs text-red-500 mt-1 font-medium">{errors.noi}</p>}
            </div>

            <div>
              <label htmlFor="cap-rate" className="block text-sm font-semibold text-foreground/80 mb-2">Capitalization Rate (%)</label>
              <input
                id="cap-rate"
                type="number"
                step="0.01"
                value={capRate}
                onChange={(e) => { setCapRate(Number(e.target.value)); setErrors({}); }}
                className="block w-full py-3 px-4 text-sm font-medium rounded-xl border border-border bg-background outline-none focus:border-primary text-foreground/80"
              />
              {errors.capRate && <p className="text-xs text-red-500 mt-1 font-medium">{errors.capRate}</p>}
            </div>

            <div className="flex gap-3 pt-4 border-t border-border">
              <button
                type="button"
                onClick={handleCalculate}
                className="flex-1 bg-primary text-white font-bold py-3 px-4 rounded-xl hover:bg-primary-hover shadow-lg shadow-primary/20 transition-all cursor-pointer text-center text-sm"
              >
                Estimate Value
              </button>
              <button
                type="button"
                onClick={handleReset}
                className="inline-flex items-center justify-center gap-1.5 border border-border hover:bg-border font-semibold py-3 px-4 rounded-xl text-foreground/70 transition-all cursor-pointer text-sm"
              >
                <RefreshCw className="h-4 w-4" />
                Reset
              </button>
            </div>
          </div>
        </div>

        {/* Results Panel */}
        <div className="lg:col-span-7 rounded-2xl border border-border bg-card p-6 shadow-sm flex flex-col justify-between">
          <div>
            <h2 className="text-xl font-bold text-foreground mb-6">Valuation Summary</h2>

            {results ? (
              <div className="space-y-4">
                <div className="rounded-xl bg-primary/5 p-4 border border-primary/10 text-center">
                  <span className="block text-xs font-bold text-foreground/50 uppercase tracking-wider font-mono">Estimated Property Value</span>
                  <span className="block text-3xl font-extrabold text-primary mt-2">
                    ${results.propertyValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </span>
                </div>
              </div>
            ) : (
              <div className="flex h-64 items-center justify-center text-foreground/40 text-sm">Enter investment parameters.</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
